// LOCALHOST 
### 
GET http://localhost:8080/toDo
### 
GET http://localhost:8080/toDo/6287cda744637c270ecdf3be

### Create contact
POST http://localhost:8080/toDo HTTP/1.1
content-type: application/json

{
    "firstName":"Togan",
    "lastName":"Cook",
    "email":"tCook@test.com",
    "favoriteColor":"blue",
    "birthday":"10/28/2001",
    "toDoSubject": "Chores",
    "toDoItem": "Clean the table"
}

// PRODUCTION Deploy
### 
GET https://cse-341-tdl.herokuapp.com/toDo 
### 
GET https://cse-341-tdl.herokuapp.com/toDo/6287cda744637c270ecdf3be 

### Create contact
POST https://cse-341-tdl.herokuapp.com/toDo HTTP/1.1
content-type: application/json

{
    "firstName":"Lston",
    "lastName":"Cook",
    "email":"aCook@test.com",
    "favoriteColor":"Red",
    "birthday":"10/28/2001",
    "toDoSubject": "Chores",
    "toDoItem": "Wash the car"
}